### ISSUE TITLE
fakeroute uses real allocated ip addresses for test networks

### ISSUE THREAD

**Issue by drt24** [libparistraceroute/fakeroute#4]
fakeroute uses 1.1.1.X as example targets. However, these IP addresses actually exist and so if fakeroute is not running or if it dies (currently trying to work out why it dies sometimes) then packets get sent out over the public internet instead which may result in strange results.

Instead either a documentation network: https://tools.ietf.org/html/rfc5737 or local addresses in 127.0.0.0/8 https://tools.ietf.org/html/rfc6890 should be used.

**Comment by ibgp2** [comment]
Ok but local address may be used also (e.g. 127.0.0.1). So I guess it is up to the user to rename the default or define wisely its own target files since these example are just... examples :-) However if you want to rename these files I'm ok with this.
